services:
  database:
    build:
      # nome cartella
      context: ./database
    ports:
      - "5050:5050"
      
  firebase:
    build:
      # nome cartella
      context: ./firebase
    ports:
      - "7070:7070"

  chat:
    build:
      # nome cartella
      context: ./chat
    ports:
      - "3000:3000"