services:
  database:
    build:
      # nome cartella
      context: ./database
    ports:
      - "4040:4040"
  gateway:
    build:
      # nome cartella
      context: ./gateway
    ports:
      - "6060:6060"
  firebase:
    build:
      # nome cartella
      context: ./firebase
    ports:
      - "7070:7070"
  frontend:
    build:
      # nome cartella
      context: ./frontend
    ports:
      - "3000:3000"
